CHANGELOG.md
README.md
lib/surgex/application.ex
lib/surgex/scout/scout.ex
test/surgex/scout/scout_test.exs

Adds extension for ScoutApm package that allows to set api key with `{:system, "SCOUT_API_KEY"}`.

Add Scout extension

---

lib/surgex/guide/code_style.ex

This rule defines that aliased modules should be used in typespecs instead of their full names. Reasoning described in doc.

Add aliases_in_typespecs code guide

---

lib/surgex/parser/parsers/resource_parser.ex
test/surgex/parser/parser_test.exs
test/surgex/parser/parsers/resource_parser_test.exs

In this PR I'm adding similar parser to `Surgex.Parser.ResourceArrayParser` called `Surgex.Parser.ResourceParser` that is responsible for parsing single instance of resource.

Add parser for handling single resource

---

lib/surgex/parser/parsers/float_parser.ex
test/surgex/parser/parsers/float_parser_test.exs

Adds optional range of acceptable values for `Surgex.Parser.FloatParser`, similar to `Surgex.Parser.IntegerParser`

Add optional range of acceptable values for `Surgex.Parser.FloatParser`.

---

lib/surgex/parser/parsers/float_parser.ex
test/surgex/parser/parser_test.exs
test/surgex/parser/parsers/float_parser_test.exs

Now `Surgex.Parser.FloatParser` takes only string as an intput. 
In this PR I extend it to handle float input as well.

Extend `Surgex.Parser.FloatParser` to take float as an input

---

lib/surgex/parser/parsers/boolean_parser.ex
test/surgex/parser/parsers/boolean_parser_test.exs

Now Surgex.Parser.BooleanParser takes only string as an input.
In this PR I extend it to handle boolean input as well.

Extend `Surgex.Parser.BooleanParser` to take Boolean as an input

---

lib/surgex/parser/parsers/float_parser.ex
test/surgex/parser/parsers/float_parser_test.exs

Since from JS standpoint there is only one type for both integers and floats parser should be able to accept any JSON number as float.

Extend FloatParser to take integer as an input

---

lib/surgex/parser/parsers/include_parser.ex
test/surgex/parser/parsers/include_parser_test.exs

Example usage:
```flat_parse(params, include: {:include, ["author", "comments", "comments.author"]})```
for request:
```GET /articles/1?include=author,comments.author```

Enable passing multiple include values

---

lib/surgex/parser/parsers/id_list_parser.ex
test/surgex/parser/parsers/id_list_parser_test.exs

Extend ability of our id_list parser to be capable of handling list types containing either strings or integer values.

Add list handling for id_list parser

---

CHANGELOG.md
lib/surgex/parser/parsers/email_parser.ex
mix.exs
test/surgex/parser/parsers/email_parser_test.exs

Backstory:
- noticed that current regexp fails for long emails due to catastrophic backtracking (f.e. `example@superlongdomainloremipsumdolor.co.uk`)
- find out that someone else fixed problem: https://github.com/surgeventures/surgex/pull/18
- run check on our big database to check if new regexp is backwards compatible and find out it is not
- learn about quirks of emails from wikipedia: https://en.wikipedia.org/wiki/Email_address#RFC_specification
- decide that very strict checking is not the best idea:
- lot of edge cases with special characters
- this parser can be used f.e. on login/password reset and we don't want to prevent anyone from accessing account because of validation
This PR contains simpler and yet backwards compatible regexp which still checks basic misspelling of emails …

Improve regexp for email parser

---

lib/surgex/parser/parser.ex
mix.exs

When using to parse more than one param, for example:
```
flat_parse(
params,
id: [:id, :required],
include: {:include, [:"customer-payment-method"]}
)
```
Dialyzer returned error:
```
The pattern can never match the type.
Pattern:
{:ok, _customer_id, _includes}
Type:
{:error, :empty_input}
| {:ok, _}
| {:error, :invalid_parameters | :invalid_pointers, [any()]}
```
I could not find any better spec definition to describe tuple with `:ok` and then one or more terms
https://github.com/elixir-lang/elixir/issues/3924

Fix typespec for flat_parse

---

CHANGELOG.md
lib/surgex/parser/parsers/boolean_parser.ex
lib/surgex/parser/parsers/integer_parser.ex
mix.exs
test/surgex/parser/parsers/boolean_parser_test.exs
test/surgex/parser/parsers/integer_parser_test.exs

Extend parsing of boolean and integer values because of change in `Plug.Test` https://github.com/phoenixframework/phoenix/issues/3605
Additional matches:
- boolean `"true" -> true` and `"false" -> false`
- integers `"" -> nil`
After the new version of Surgex is added to all our apps we can update the Plug to `v1.12`.

Extend parsing of boolean and integer values

---

CHANGELOG.md
mix.exs

The previous version should be minor not patch.
[SemVer](https://semver.org/)
> Bug fixes not affecting the API increment the patch version, backwards compatible API additions/changes increment the minor version, and backwards incompatible API changes increment the major version.

Bump minor version to v4.3.0

---

CHANGELOG.md
lib/surgex/parser/parsers/resource_id_parser.ex
mix.exs
test/surgex/parser/parsers/id_parser_test.exs
test/surgex/parser/parsers/resource_id_parser_test.exs

Extend parsing of ResourceID, empty string should be parsed the same as `nil` value.

Extend parsing of ResourceID

---

CHANGELOG.md
lib/surgex/parser/parsers/resource_array_parser.ex
mix.exs
test/surgex/parser/parsers/resource_array_parser_test.exs

Update `Surgex.Parser.ResourceArrayParser` to support invalid parameters, it used to support only invalid pointers.

Update Surgex.Parser.ResourceArrayParser to support invalid parameters

---

CHANGELOG.md
lib/surgex/parser/parsers/email_parser.ex
lib/surgex/parser/parsers/string_parser.ex
lib/surgex/parser/parsers/uuid_parser.ex
mix.exs
test/surgex/parser/parser_test.exs
test/surgex/parser/parsers/email_parser_test.exs
test/surgex/parser/parsers/string_parser_test.exs
test/surgex/parser/parsers/uuid_parse_test.exs

* Add `regex` option to `StringParser`, allowing specifying any kind of format constraints on an input
* Rewrite `EmailParser` to use the new option
* Add UUID parser limiting input to only valid UUIDs

Regex options in StringParser + UUID parser

---

.circleci/config.yml

Addresses [CD-619](https://shedul.atlassian.net/browse/CD-619).
Update of elixir-orb for circleci usage from 0.0 -> 0.2
- Only change between 0.1 -> 0.2 is an updated postgres image and a new command.
image: 'circleci/postgres:12-postgis-ram' -> image: 'cimg/postgres:12.9-postgis' (https://github.com/surgeventures/elixir-orb/pull/14/files), both images running postgres 12.9
- Few more changes in 0.0 -> 0.1
This is related to the deprecation of the legacy convenience images from circleci (circleci/ -> next-gen cimg/) from Dec 2021

[CD-619] elixir-orb update - postgres circleci convience img update

---

CHANGELOG.md
lib/surgex/parser/parsers/default_parser.ex
mix.exs
test/surgex/parser/parsers/default_parser_test.exs

This PR introduces a new parser that substitutes any empty value with the provided default value. By default, empty values are defined as `nil` and empty string, but can be redefined per specific use case, see usage examples:
```elixir
parse(
params,
sort_order: [:string, {:default, "asc"}],
status: :string,
search: :string,
)
```
```elixir
parse(
params,
sort_order: [:string],
status: [
:resource_array,
{:default, ["enabled"], empty_values: [[]]}
],
search: :string,
)
```
add the `:default` parser first in the list of parsers to ensure that the provided default value is passed through all other parsers.
Notes:
Alternatively, we could add defaults to `params` before passing them to the `parse` function. But then we would be spreading param-related concerns across `Surgex` and the specific …

Add default input value parser

---

lib/surgex/parser/parsers/decimal_parser.ex
mix.exs
test/surgex/parser/parsers/decimal_parser_test.exs

It turn's out that Decimal.parse can have different type of output depending on the module version
`{Decimal.new(10), ""}`, `{:ok, Decimal.new(10)}`
also adds some tests

fix decimal parsing on different version of the module

---

lib/surgex/parser/parsers/id_parser.ex
lib/surgex/parser/parsers/slug_or_id_parser.ex
test/surgex/parser/parsers/id_parser_test.exs
test/surgex/parser/parsers/slug_or_id_parser_test.exs

We are getting errors such as [this one](https://sentry.io/organizations/surge-ventures/issues/2512676631) because certain params are out of the max integer range for Postgres, but are getting through the controller layer and being used in queries.
A good, DRY approach may to be to set a max id range in this library.

Set default max for IdParser

---

lib/surgex/parser/parsers/id_list_parser.ex
mix.exs
test/surgex/parser/parsers/id_list_parser_test.exs

It was failing when parsing a list containing a `nil` value:
```
iex> Surgex.Parser.IdListParser.call([nil])
** (FunctionClauseError) no function clause matching in Surgex.Parser.IdListParser.reduce_ids/2
The following arguments were given to Surgex.Parser.IdListParser.reduce_ids/2:
nil
{:ok, []}
Attempted function clauses (showing 4 out of 4):
defp reduce_ids(_, {:error, reason})
defp reduce_ids(id_string, {:ok, previous_ids}) when is_binary(id_string)
defp reduce_ids(id, {:ok, previous_ids}) when is_integer(id) and id > 0
defp reduce_ids(id, {:ok, _previous_ids}) when is_integer(id)
```
It's because the previous implementation expected the list items always to be a string or an integer but we had cases when FE was sending a list containing `nil` as well.

Handle nil values in IdListParser

---

CHANGELOG.md
lib/surgex/parser/parser.ex
mix.exs
test/surgex/parser/parser_test.exs

The current behavior of `Surgex.Parser` returns 400 error when it receives unexpected parameters. This causes issues with parameters that get deleted over time, basically the changes aren't backward compatible until all previous versions stop sending the to be deleted parameter.

Discard unexpected parameters in Parser instead of returning 400 error

---

CHANGELOG.md
lib/surgex/parser/parser.ex
lib/surgex/sentry/sentry.ex
mix.exs

Even though this compiles fine on its own, when you depend on Surgex, you can't compile it because you get
```
❯ mix deps.compile surgex
==> surgex
Compiling 47 files (.ex)
== Compilation error in file lib/surgex/parser/parser.ex ==
** (CompileError) lib/surgex/parser/parser.ex:67: Jabbax.Document.Resource.__struct__/0 is undefined, cannot expand struct Jabbax.Document.Resource. Make sure the struct name is correct. If the struct name exists and is correct but it still cannot be found, you likely have cyclic module usage in your code
expanding struct: Jabbax.Document.Resource.__struct__/0
lib/surgex/parser/parser.ex:67: Surgex.Parser.parse/2
could not compile dependency :surgex, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix …
```

Ensure Jabbax and Plug are loaded before defining a module in which they're required

---

CHANGELOG.md
lib/surgex/data_pipe/follower_sync.ex
mix.exs

`Logger.warn` is deprecated. Using `Logger.warning` instead.

Fixed deprecation by using Logger.warning
